questions = [
    { "question": "The government should have the right to monitor all digital communications to prevent crime.", "effect": { "govt": -10 } },
    { "question": "State stability is more important than the right of individuals to express extreme opinions.", "effect": { "govt": -10 } },
    { "question": "Laws should protect people from themselves, such as banning harmful drugs.", "effect": { "govt": -10 } },
    { "question": "A citizen always has a moral right to disobey a government they find oppressive.", "effect": { "govt": 10 } },
    { "question": "Public safety is a fair trade for the presence of mass surveillance in urban areas.", "effect": { "govt": -10 } },
    { "question": "The state should never be allowed to keep 'classified' secrets from its own citizens.", "effect": { "govt": 10 } },
    { "question": "The government has the right to mandate civil or military service for the greater good.", "effect": { "govt": -10 } },

    { "question": "Policy decisions should be made by unelected experts rather than by popular vote.", "effect": { "dem": -10 } },
    { "question": "A strong, decisive leader is more effective than one driven by consensus and debate.", "effect": { "dem": -10 } },
    { "question": "The right to vote should be earned through service or a demonstration of competence.", "effect": { "dem": -10 } },
    { "question": "Every major national law should be subject to a direct referendum by the people.", "effect": { "dem": 10 } },
    { "question": "Political parties are often a source of unnecessary conflict and should be replaced by a unified movement.", "effect": { "dem": -10 } },
    { "question": "The judiciary must have the power to block any executive action that violates established rights.", "effect": { "dem": 10 } },
    { "question": "Regular, fair elections are the only legitimate way to transfer power in a state.", "effect": { "dem": 10 } },

    { "question": "A single set of laws should apply to every person in the country to ensure total equality.", "effect": { "fed": -10 } },
    { "question": "Local communities should be allowed to set their own rules, even if they conflict with national law.", "effect": { "fed": 10 } },
    { "question": "Any region or group of people should have the legal right to peacefully secede.", "effect": { "fed": 10 } },
    { "question": "The central government should manage all national resources to prevent regional wealth gaps.", "effect": { "fed": -10 } },
    { "question": "The most effective government is the one that is closest to the people at the local level.", "effect": { "fed": 10 } },
    { "question": "A centralized education system is necessary to forge a unified national identity.", "effect": { "fed": -10 } },
    { "question": "Regions should be 'laboratories of democracy,' free to try wildly different policy approaches.", "effect": { "fed": 10 } },

    { "question": "International treaties should have authority over the internal laws of a nation.", "effect": { "dipl": 10 } },
    { "question": "My nation should prioritize its own interests even if it harms the global community.", "effect": { "dipl": -10 } },
    { "question": "We have a moral responsibility to intervene in other nations to stop human rights abuses.", "effect": { "dipl": 10 } },
    { "question": "Economic and political globalization is a positive force that brings humanity closer together.", "effect": { "dipl": 10 } },
    { "question": "The unique cultural heritage of my nation must be protected from foreign influence at any cost.", "effect": { "dipl": -10 } },
    { "question": "Ultimately, national governments should be replaced by a single global authority.", "effect": { "dipl": 10 } },
    { "question": "Providing foreign aid to developing nations is an essential duty of a civilized country.", "effect": { "dipl": 10 } },

    { "question": "Every human being should have the right to live and work in any country they choose.", "effect": { "bord": 10 } },
    { "question": "A nation without a strictly controlled and physical border is not truly a nation.", "effect": { "bord": -10 } },
    { "question": "Immigrants should be expected to fully assimilate into the host nation's culture.", "effect": { "bord": -10 } },
    { "question": "Free trade without tariffs is always better than economic protectionism.", "effect": { "bord": 10 } },
    { "question": "The influx of different cultures makes a society stronger and more resilient.", "effect": { "bord": 10 } },
    { "question": "Foreign workers should only be allowed entry if there is a shortage of local labor.", "effect": { "bord
